/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_samples_tutorial2_Tutorial2Activity */

#ifndef _Included_org_opencv_samples_tutorial2_Tutorial2Activity
#define _Included_org_opencv_samples_tutorial2_Tutorial2Activity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opencv_samples_tutorial2_Tutorial2Activity
 * Method:    mtcnnDetect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_tutorial2_Tutorial2Activity_mtcnnDetect
  (JNIEnv *, jclass , jlong);

#ifdef __cplusplus
}
#endif
#endif
